# Generated by Django 4.2.6 on 2023-10-20 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plane', '0001_initial'),
        ('airline', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_c', models.CharField(max_length=256)),
                ('to', models.CharField(max_length=256)),
                ('price', models.PositiveIntegerField()),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airline.airline')),
                ('plane', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plane.plane')),
            ],
        ),
    ]
