# Generated by Django 4.2.6 on 2023-10-20 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('characteristics', models.CharField(max_length=256)),
                ('capacity', models.PositiveIntegerField()),
            ],
        ),
    ]
